name: pks_4337_sdk
description: An Account Abstraction (4337) Development kit, for quickly building mobile web3 apps.
version: 1.0.0+1
homepage: https://github.com/infinit3-labs/4337-Dart.git
environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    webauthn: ^0.2.1
    web3dart: ^2.6.1
    webcrypto: ^0.5.3
    asn1lib: ^1.5.0
    uuid: ^3.0.7
    crypto: ^3.0.3
    cbor: ^6.1.1
    flutter_secure_storage: ^9.0.0
    local_auth: ^2.1.7
    http: ^0.13.5
    pointycastle: ^3.7.3
    walletconnect_flutter_v2: ^2.0.8
    bip39: ^1.0.6
    bip32_bip44: ^1.0.0
    eth_sig_util: ^0.0.9
    dio: ^5.3.2
    ens_dart: ^1.0.0
    dio_cache_interceptor: ^3.4.3
    freezed_annotation: ^2.4.1
    json_annotation: ^4.8.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    web3dart_builders: ^0.0.7
    build_runner: ^2.4.6

    flutter_lints: ^2.0.0
    freezed: ^2.4.1
    json_serializable: ^6.7.1
    mockito: ^5.4.2

